### ISSUE TITLE
Updated install instructions with Ubuntu packaging

### ISSUE THREAD

**Issue by litlfred** [openhie/ansible-openinfoman-hwr#4]
Hi Ryan,
The OpenInfoMan side of things now has updated easier install instructions:

sudo add-apt-repository ppa:openhie/release
sudo apt-get update
sudo apt-get install openinfoman openinfoman-ilr openinfoman-hwr

**Comment by yatesr** [comment]
Awesome!  I will add this as the default install method for deployment. It looks like it does bring in a lot of desktop related packages as dependencies (X11, libgnome, libgtk).  Is that intentional or could that be slimmed down for headless installs?

**Comment by litlfred** [comment]
I didn’t bring those in directly, so it’s somewhere in the dependencies.  Doing:
 
aptitude why libgnome2-0
i   openinfoman   PreDepends default-jre | openjdk-7-jre
i A openjdk-7-jre Recommends libgnome2-0    

I see that openjdk is the culprit.  Not sure we can fix this.


Cheers,
-carl

**Comment by litlfred** [comment]
BTW.. I am working on getting the HWR Management Interface packaged as well.   I am at the point where I need to test on a clean install, but I think it is almost ready.

**Comment by yatesr** [comment]
For openjdk-7 you should be able to bring in openjdk-7-jre-headless instead of openjdk-7-jre.  It shouldn't bring in any of the X-11, gnome stuff.

**Comment by litlfred** [comment]
this should be fixed with the latest package build 1.0.25:
  https://github.com/openhie/openinfoman/commit/e82ed7db493cdec73ad6e9b7c01f7b7cb0d08fd1
though I didn't have a chance to check it out
